version: '3.7'

services:
  web:
    build: ./project
    command: ./run
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8002:8000

  web-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
